repos:
  # 1. Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # enforce github rule
      - id: no-commit-to-branch
        args: [--branch, main]

      # check files
      - id: check-toml
      - id: check-yaml
      - id: check-json

      # format files
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer

      # check code
      - id: debug-statements
      - id: end-of-file-fixer

      # check tests
      - id: name-tests-test
        args: ["--pytest-test-first"]

  # 2. Bandit for security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ['--configfile', 'bandit.yaml']

  # 3. Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        args: [".", "--config", "ruff.toml"]
      - id: ruff-format
        args: ["--check", "--config", "ruff.toml"]

  # 4. Pyright for type checking
  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.404
  #   hooks:
  #     - id: pyright
  #       args: ["--config", "pyrightconfig.json"]
