[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "solfacil"
version = "0.1.0"
description = "Solfacil Python packages and tools"

requires-python = ">=3.12"
dependencies = [
    "redis>=6.2.0"
]

[tool.hatch.build.targets.sdist]
include = [
    "solfacil"
]

[tool.hatch.build.targets.wheel]
include = [
    "solfacil"
]
