
name: Python Continuous Integration

on:
  push:

env:
  PYTHON_VERSION: 3.12
  DEPENDENCIES_FILE: requirements/development.txt

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip wheel setuptools

      - name: 'Install dependencies - pip: ${{ env.DEPENDENCIES_FILE }}'
        run: |
          pip install -r ${{ env.DEPENDENCIES_FILE }}
      
      - name: Install dependencies - package[editable]
        run: |
          pip install -e .
        
      - name: Linter - Ruff
        run: |
          ruff check solkit

      - name: Formatter - Ruff
        run: |
          ruff format --check

      - name: Typecheck - Pyright
        run: |
          pyright --project pyrightconfig.json
      
      - name: Test - Pytest - Unit
        run: |
          pytest tests/unit
      
      # - name: Test - Pytest - Integration
      #  run: |
      #    pytest tests/integration
