
name: Python Continuous Integration

on:
  push:
    branches:
      - main
    
env:
  PYTHON_VERSION: 3.12
  DEPENDENCIES_FILE: requirements/development.txt

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install dependencies - ${{ env.DEPENDENCIES_FILE }}'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r ${{ env.DEPENDENCIES_FILE }}
        
      - name: Ruff - Linter
        run: |
          ruff check solkit

      - name: Ruff - Formatter
        run: |
          ruff format --check

      - name: Pyright - Typecheck
        run: |
          pyright --verifytypes solkit
